In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv("transactions_data.csv")

In [3]:
df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [5]:
df2= pd.read_csv("users_data.csv")

In [7]:
df2.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [ ]:
data= pd.merge(df, df2, how="outer")

In [38]:
data.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,...,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,Male,858 Plum Avenue,43.59,-70.33,$29237,$59613,$36199,763.0,4.0
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,Female,113 Burns Lane,30.44,-87.18,$22247,$45360,$14587,704.0,3.0
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,Male,6035 Forest Avenue,40.84,-73.87,$13461,$27447,$80850,673.0,5.0
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,Male,840 Elm Avenue,33.89,-98.51,$13705,$27943,$18693,681.0,4.0
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,Female,6016 Little Creek Boulevard,47.61,-122.30,$37485,$76431,$115362,716.0,5.0

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13305915 entries, 0 to 13305914
Data columns (total 25 columns):
 #   Column             Dtype
---  ------             -----
 0   id                 int64
 1   date               object
 2   client_id          int64
 3   card_id            int64
 4   amount             object
 5   use_chip           object
 6   merchant_id        int64
 7   merchant_city      object
 8   merchant_state     object
 9   zip                float64
 10  mcc                int64
 11  errors             object
 12  current_age        float64
 13  retirement_age     float64
 14  birth_year         float64
 15  birth_month        float64
 16  gender             object
 17  address            object
 18  latitude           float64
 19  longitude          float64
 20  per_capita_income  object
 21  yearly_income      object
 22  total_debt         object
 23  credit_score       float64
 24  num_credit_cards   float64
dtypes: float64(9), int64(5), object(11)
memory usage: 2.5+ GB

In [24]:
data.shape

(13305915, 25)

In [25]:
data.isnull().sum()

id                          0
date                        0
client_id                   0
card_id                     0
amount                      0
use_chip                    0
merchant_id                 0
merchant_city               0
merchant_state        1563700
zip                   1652706
mcc                         0
errors               13094522
current_age          13305915
retirement_age       13305915
birth_year           13305915
birth_month          13305915
gender               13305915
address              13305915
latitude             13305915
longitude            13305915
per_capita_income    13305915
yearly_income        13305915
total_debt           13305915
credit_score         13305915
num_credit_cards     13305915
dtype: int64

In [ ]:
merged = pd.merge(transactions, users, on='client_id', how='inner')